### PR TITLE
Ingest nil errors

### LINKED ISSUE #157: nil errors when regex fails on ingest
```
WARN [2016-02-09 15:19:15]: /Users/chuck_mccallum/Downloads/2015_OV_MASTERS_FINAL_pbcoreRENAMED.zip :: A_3135488CBB9E467B9F0684BC930E6498.xml : undefined method `id' for nil:NilClass
```

https://github.com/WGBH/openvault3/compare/ingest-nil-errors is a step in the right direction: Need to test it.

### PR DESCRIPTION
**Pull request by mccalluc**
@afred? Fix #157. 

(AAPB does some solid testing of the output of the tests, and we could do something like that here... except that the way it works by capturing all output makes the tests themselves a pain to debug because it captures the pry output itself. Also, the ingest machinery here is a lot less complicated, so I'm more comfortable with the tests essentially being our usage of it.)

### CODE REVIEW

File: scripts/lib/pb_core_ingester.rb [hunk 1]
```diff
@@ -46,9 +46,9 @@ def ingest(opts)
       Zip::File.open(path) do |zip_file|
         zip_file.each do |entry|
           begin
-            ingest_xml_no_commit(entry.get_input_stream.read)
+            ingest_xml_no_commit(entry.get_input_stream.read) ||
+              $LOG.warn("No match. Skipping #{path} :: #{entry.name} ")
```
Comment (afred) [inline scripts/lib/pb_core_ingester.rb]: @mccalluc under what condition would `entry.get_input_stream.read` be untrue?
